### ISSUE TITLE
TARDIS Time Machine

### ISSUE THREAD

**Issue by fuddl** [hfg-gmuend/openmoji#182]
[TARDIS on Wikipedia](https://en.wikipedia.org/wiki/TARDIS)

![TARDIS-TIME-MACHINE](https://user-images.githubusercontent.com/842548/79682617-fe4ac280-8223-11ea-8242-6e93cf853f95.png)
[Figma Link](https://www.figma.com/file/sZZLEmdnMTOAxq0mTgO4WN/tardis-emoji?node-id=1%3A29)

Any suggestions? Ideas?

**Comment by carlinmack** [comment]
wow! very good, could you please select the 8 panels and then align them centred with the page?

**Comment by fuddl** [comment]
how about this?

![TARDIS-TIME-MACHINE](https://user-images.githubusercontent.com/842548/79690354-500e3f80-825a-11ea-8284-5e991fa8ae1a.png)

**Comment by carlinmack** [comment]
Yes very good, open a PR :)

Also I see that you are using figma, let me know if you face difficulties in exporting a clean SVG, it'd be good for us to have a guide for figma here https://openmoji.org/styleguide/#file_export

**Comment by fuddl** [comment]
## Figma

@carlinmack wrote:
> Also I see that you are using figma, let me know if you face difficulties in exporting a clean SVG, it'd be good for us to have a guide for figma here https://openmoji.org/styleguide/#file_export

I had to make some manual adjustments which could be totally done by a script. Unfortunately figma does not offer a lot of export options.

## Non-standard colors

I deliberately a [darker shade of blue](https://tardis.fandom.com/wiki/TARDIS_blue). What should I do about this message? 

```
  1) Color
       Fill colors included in OpenMoji color palette?
          E149.svg should have correct fill colors:
     AssertionError: expected [ Array(27) ] to include '#003b6f'
      at query.forEach.el (test/color.js:31:34)
      at Proxy.forEach (<anonymous>)
      at Context.<anonymous> (test/color.js:30:15)
```

**Comment by carlinmack** [comment]
you can use #1e50a0 there's three colours that aren't on the styleguide for some reason. These are all the colours

```css
* {
    /* blues */
    color: #92d3f5;
    color: #61b2e4;
    /* reds */
    color: #ea5a47;
    color: #d22f27;
    /* greens */
    color: #b1cc33;
    color: #5c9e31;
    /* yellows */
    color: #fcea2b;
    color: #f1b31c;
    /* greys */
    color: #ffffff;
    color: #d0cfce;
    color: #9b9b9a;
    color: #3F3F3F;
    color: #000000;
    /* oranges */
    color: #f4aa41;
    color: #e27022;
    /* pinks */
    color: #ffa7c0;
    color: #e67a94;
    /* purples */
    color: #b399c8;
    color: #8967aa;
    /* browns */
    color: #a57939;
    color: #6a462f;

    /* navy */
    color: #1e50a0;
    /* maroon */
    color: #781e32;
    /* dark green */
    color: #186648;
}

/* "skintones": { */

fitzpatrick {
    color: #fadcbc;
    color: #debb90;
    color: #c19a65;
    color: #a57939;
    color: #6a462f;
}

shadow {
    color: #debb90;
    color: #c19a65;
    color: #a57939;
    color: #6a462f;
    color: #352318;
}

hair {
    color: #a57939;
    color: #fcea2b;
    color: #6a462f;
    color: #000000;
    color: #000000;
}
```
