### ISSUE TITLE
optimisation for web embedding: split into blocks

### ISSUE THREAD

**Issue by loominade** [hfg-gmuend/openmoji#409]
right now it is pretty inefficient to use the font on the web since the font file is very large. Most of it wouldn't be used in a single document anyway. Therefore I propose to deliver font files as [smaller chunks, like I did here](https://github.com/loominade/loomicons/blob/master/build/loomicons.css).

The idea is, to deliver smaller font files by blocks and supply the browsers with the mapping which file contains which glyph:

```css
/* Arrows */
@font-face {
  font-family: Openmoji;
  src: url(openmoji/arrows.woff2) format('woff2');
  /* contains glyphs: ←,↑,→,↓ */
  unicode-range: U+2190-2193;
}

/* Miscellaneous Symbols and Pictographs */
@font-face {
  font-family: Openmoji;
  src: url(openmoji/misc-symbols-and-pictographs.woff2) format('woff2');
  /* contains glyphs: 📖,🗙 */
  unicode-range: U+1F4D6,U+1F5D9;
}

/* … */

```

It would be necessary to generate a companion css file for each version of the font.
